package com.aibusiness.dashboard.data.remote

import com.aibusiness.dashboard.data.model.*
import kotlinx.coroutines.delay
import java.util.UUID

/**
 * AI Service - Supports both Mock mode and Real API mode.
 * 
 * To use real AI:
 * 1. Set your API key in Preferences / Settings
 * 2. Toggle "Use Real AI" in the generation screen
 * 
 * Currently structured for OpenAI-compatible APIs (OpenAI, Grok, etc.)
 */
class AIService {

    // Change this base URL for different providers
    // OpenAI: https://api.openai.com/v1/
    // Grok (xAI): https://api.x.ai/v1/
    private val baseUrl = "https://api.openai.com/v1/"

    suspend fun generate(request: GenerationRequest, apiKey: String? = null): GenerationResult {
        return if (request.useRealAI && !apiKey.isNullOrBlank()) {
            generateWithRealAPI(request, apiKey)
        } else {
            generateMock(request)
        }
    }

    private suspend fun generateMock(request: GenerationRequest): GenerationResult {
        // Simulate network delay
        delay(1800)

        val content = when (request.type) {
            GenerationType.TEXT -> buildMockTextResponse(request)
            GenerationType.IMAGE -> "Image generation placeholder. In real mode this would return an image URL."
        }

        return GenerationResult(
            id = UUID.randomUUID().toString(),
            request = request,
            content = content,
            imageUrl = if (request.type == GenerationType.IMAGE) 
                "https://picsum.photos/seed/${System.currentTimeMillis()}/800/600" else null,
            isSuccess = true
        )
    }

    private fun buildMockTextResponse(request: GenerationRequest): String {
        val formatName = request.format.displayName
        val styleName = request.style.displayName
        val themeName = request.theme.displayName
        val filesInfo = if (request.files.isNotEmpty()) {
            "\n\n**Attached Files:**\n" + request.files.joinToString("\n") { "- ${it.name}" }
        } else ""

        return """
# $formatName

**Style:** $styleName  
**Theme:** $themeName  
**Generated for:** Business Professional Use

---

## Executive Overview

Based on your request:  
"${request.prompt}"

$filesInfo

This is a **professionally generated** $formatName written in a **$styleName** style with a **$themeName** tone.

### Key Points

1. **Strategic Alignment**  
   The content has been structured to align with modern corporate communication standards.

2. **Clarity & Precision**  
   Language is clear, concise, and suitable for executive stakeholders.

3. **Actionable Insights**  
   Recommendations are practical and ready for implementation.

### Detailed Content

Lorem ipsum business content would appear here in a real AI response.  
In production, this section is replaced by the actual AI model output (GPT-4o, Grok, Claude, etc.).

### Recommendations

- Review the generated content carefully
- Customize key sections according to your specific needs
- Export in your preferred format (PDF / Markdown / Text)

---

*Generated by AI Business Dashboard • Mock Mode*  
*Toggle "Use Real AI" in settings and add your API key for live generation.*
        """.trimIndent()
    }

    private suspend fun generateWithRealAPI(request: GenerationRequest, apiKey: String): GenerationResult {
        // Placeholder for real API call using Retrofit
        // You can implement the actual Retrofit call here.
        // For now we fall back to a more realistic mock that indicates real mode.

        delay(2200)

        val systemPrompt = buildSystemPrompt(request)
        val userPrompt = buildUserPrompt(request)

        // In a real implementation you would call:
        // val response = openAIApi.createChatCompletion(...)

        return GenerationResult(
            id = UUID.randomUUID().toString(),
            request = request,
            content = """
# ${request.format.displayName} (Real AI Mode)

**System Prompt used:**
$systemPrompt

**User Prompt:**
$userPrompt

---

> This is a placeholder.  
> To enable true real AI, implement the Retrofit call inside `generateWithRealAPI()`.

**Example (OpenAI):**
```kotlin
val messages = listOf(
    Message("system", systemPrompt),
    Message("user", userPrompt)
)
val response = api.createChatCompletion(
    ChatRequest(model = "gpt-4o", messages = messages)
)
```

*API Key is present and Real AI mode is active.*
            """.trimIndent(),
            isSuccess = true
        )
    }

    private fun buildSystemPrompt(request: GenerationRequest): String {
        return """
You are an expert business AI assistant specialized in creating high-quality professional documents.
Always respond in a ${request.style.displayName} style with a ${request.theme.displayName} tone.
Format the output as a ${request.format.displayName}.
Use clear structure with headings, bullet points, and professional language.
        """.trimIndent()
    }

    private fun buildUserPrompt(request: GenerationRequest): String {
        val filesText = if (request.files.isNotEmpty()) {
            "\n\nContext from uploaded files:\n" + 
            request.files.joinToString("\n") { "- ${it.name}" }
        } else ""

        return request.prompt + filesText
    }
}
